image: phpdocker/phpdocker:7.2
cache:
  paths:
  - vendor/
before_script:
  - curl -sSOL https://cecil.app/cecil.phar
  - php cecil.phar --version
  - composer install
pages:
  script:
  - php cecil.phar build --verbose --destination=public
  artifacts:
    paths:
    - public
  only:
  - master
