title: Some Hike it Hot
baseline: Your blogging assistant
description: A blog documenting the good, bad, and sweaty times.
baseurl: /
canonicalurl: true
keywords: Cecil, Static Site Generator, SSG
author: Bash & Buffy
date:
  format: j F Y
  timezone: Australia/Melbourne
theme:
  - hyde
  - netlify
  - netlify-cms
postprocess:
  enabled: true
