title: "The Butler"
baseline: "Your blogging assistant."
description: "A ready to use static blog, powered by Cecil."
keywords: "Cecil, Static Site Generator, SSG"
author: "Arnaud Ligny"
baseurl: "/"
canonicalurl: true
theme:
  - hyde
  - netlify-cms
date:
  format: "j F Y"
  timezone: "Europe/Paris"
output:
  formats:
    - name: netlify_redirects
      mediatype: "text/plain"
      extension: ""
virtualpages:
  - path: _redirects
    output: netlify_redirects
postprocess:
  enabled: true
