backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    description: >
      Posts listed in the 'Blog' Section and in the RSS feed.
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}      
      - {label: "Published?", name: "published", widget: "boolean", default: false, required: true}
  - name: "pages"
    label: "Pages"
    description: >
      Single pages: About, 404, etc.
    delete: false
    files:
      - name: "404"
        label: "404"
        file: "content/404.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "404"}
          - {label: "Permalink", name: "permalink", widget: "string", default: "404.html"}
          - {label: "Text", name: "body", widget: "markdown"}
          - {label: "Published?", name: "published", widget: "hidden", default: true}
      - name: "about"
        label: "About"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "About"}
          - {label: "Text", name: "body", widget: "markdown"}
          - label: "Menu"
            name: "menu"
            widget: "object"
            fields:
              - label: "Main"
                name: "main"
                widget: "object"
                fields:
                  - {label: "Weight", name: "weight", widget: "number", default: 101, valueType: "int"}
                  - {label: "Published?", name: "published", widget: "boolean", default: false, required: true}
  - name: "settings"
    label: "Settings"
    description: >
      Blog settings.
    delete: false
    editor:
      preview: false
    files:
      - name: "config"
        label: "Configuration"
        file: "phpoole.yml"
        fields:
          - label: "Site"
            name: "site"
            widget: "object"
            fields:
              - {label: "Base URL", name: "baseurl", widget: "string", default: "/"}
              - {label: "Title", name: "title", widget: "string", default: "Cecil"}
              - {label: "Baseline", name: "baseline", widget: "string", default: "Your blog's butler."}
              - {label: "Description", name: "description", widget: "string", default: "Your blog's butler, powered by PHPoole."}
          - {label: "Theme", name: "theme", widget: "string", default: "hyde"}
