backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "Posts"
    name: "posts"
    description: >
      Posts listed in the 'Blog' Section and in the RSS feed.
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}      
      - {label: "Published?", name: "published", widget: "boolean", default: false, required: true}
  - label: "Pages"
    name: "pages"
    description: >
      Single pages: About, 404, etc.
    delete: false
    files:
      - label: "404"
        name: "404"
        file: "content/404.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "404"}
          - {label: "Permalink", name: "permalink", widget: "string", default: "404.html"}
          - {label: "Text", name: "body", widget: "markdown"}
          - {label: "Published?", name: "published", widget: "hidden", default: true}
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "About"}
          - {label: "Text", name: "body", widget: "markdown"}
          - label: "Menu"
            name: "menu"
            widget: "object"
            fields:
              - label: "Main"
                name: "main"
                widget: "object"
                fields:
                  - {label: "Weight", name: "weight", widget: "number", default: 101, valueType: "int"}
          - {label: "Published?", name: "published", widget: "boolean", default: false, required: true}
  - label: "Settings"
    name: "settings"
    description: >
      Blog settings.
    delete: false
    editor:
      preview: false
    files:
      - label: "Configuration"
        name: "config"
        file: "phpoole.yml"
        fields:
          - label: "Site"
            name: "site"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Cecil", required: true}
              - {label: "Baseline", name: "baseline", widget: "string", default: "Your blog's butler.", required: true}
              - {label: "Base URL", name: "baseurl", widget: "string", default: "/", required: true}
              - {label: "Use canonical URL", name: "canonicalurl", widget: "boolean", default: true, required: true}
              - {label: "Description", name: "description", widget: "string", default: "Your blog's butler, powered by PHPoole.", required: true}
              - label: "Pagintation"
                name: "paginate"
                widget: "object"
                fields:
                  - {label: "Posts per page", name: "max", widget: "number", default: 5, valueType: "int", required: true}
                  - {label: "Pagination path", name: "path", widget: "string", default: "page", required: true}
              - label: "Date"
                name: "date"
                widget: "object"
                fields:
                  - {label: "Format", name: "format", widget: "string", default: "j F Y", required: true}
                  - {label: "Time zone", name: "timezone", widget: "string", default: "Europe/Paris", required: true}
          - {label: "Theme", name: "theme", widget: "string", default: "hyde"}
